"""HyDE — Hypothetical Document Embeddings.

The dense retrieval pass embeds the user's question and compares
against chunk embeddings. Questions are short and abstract; chunks
are answer-shaped prose. The vector distance between
"how do I move a spec from CR to REC?" and the chunk that ACTUALLY
explains the CR-to-REC transition is bigger than the distance
between a hypothetical short answer to that question and the
same chunk.

HyDE addresses this by asking the LLM to draft a brief hypothetical
answer FIRST, then using the hypothetical's embedding for dense
retrieval. The hypothesis is intentionally low-quality — it may
even be wrong; what we want is the topical / vocabulary shape of an
answer-style passage, not factual accuracy. The actual answer the
user sees is still generated by the main workflow against the
RETRIEVED grounded excerpts; HyDE only widens recall.

Cost: one extra LLM call per request (~200ms-2s depending on
provider), in parallel with the existing ``rewrite_query`` call so
the wall-clock overhead is bounded by the slower of the two.

Failure handling: any error returns an empty passage, the workflow
silently falls back to the standard retrieval path (which is still
hybrid BM25 + TF-IDF + dense-on-the-bare-query).
"""

from __future__ import annotations

import logging
import threading
from collections import OrderedDict
from dataclasses import dataclass

from app.core.config import Settings
from app.services.llm_router import JSONGenerator


logger = logging.getLogger(__name__)


_HYDE_CACHE_LIMIT = 256
_hyde_cache: OrderedDict[str, "HypotheticalPassageResult"] = OrderedDict()
_hyde_cache_lock = threading.Lock()


@dataclass(frozen=True)
class HypotheticalPassageResult:
    """Output of ``generate_hypothetical_passage``."""

    passage: str
    """The drafted passage — may be empty when the LLM call failed."""

    model: str
    error: str | None = None


# Cap the passage size: too long and BM25 noise overwhelms the
# signal; too short and there's no dense gain over the original
# query.
_MAX_CHARS = 600


def _prompt(user_message: str) -> str:
    """Hand-crafted prompt asking the model for a SHORT,
    answer-shaped passage rather than a literal answer.

    We're intentionally NOT giving the model the corpus — that would
    make HyDE redundant with normal generation. Wanted: vocabulary
    + topical shape of "what an answer would look like".
    """
    return f"""You are sketching a hypothetical answer that a W3C Process expert MIGHT
write to the following question. Your draft will NOT be shown to the
user — it is used only to broaden a retrieval search across the W3C
Process Document and the Guidebook. Accuracy does not matter; what
matters is using the right W3C vocabulary, naming the relevant Process
stages / chapters / forms / roles, and writing in the prose style of
an actual answer (not a question, not a list of keywords).

Question: {user_message}

Output JSON: {{"passage": "<2-4 sentence draft answer mentioning the
relevant W3C terms and Process artifacts; 100-400 chars>"}}"""


def generate_hypothetical_passage(
    user_message: str,
    *,
    settings: Settings,
    client: JSONGenerator,
    model: str | None = None,
) -> HypotheticalPassageResult:
    """Return a hypothetical answer-shaped passage for ``user_message``.

    Cached process-wide by ``(message, model)`` so repeat questions
    (and the eval harness's pattern of running the same questions
    many times) don't burn rate-limit quota.
    """
    selected_model = model or settings.llm_router_model or settings.llm_model
    cache_key = f"{selected_model}::{user_message.strip()}"
    with _hyde_cache_lock:
        cached = _hyde_cache.get(cache_key)
        if cached is not None:
            _hyde_cache.move_to_end(cache_key)
            return cached

    try:
        payload = client.generate_json(
            model=selected_model, prompt=_prompt(user_message), num_predict=220
        )
    except Exception as exc:  # pragma: no cover - external model fallback
        logger.warning("HyDE LLM call failed; continuing without HyDE", exc_info=exc)
        result = HypotheticalPassageResult(
            passage="", model=selected_model, error=type(exc).__name__
        )
        _store(cache_key, result)
        return result

    passage = ""
    if isinstance(payload, dict):
        candidate = payload.get("passage") or payload.get("answer") or payload.get("draft")
        if isinstance(candidate, str):
            passage = " ".join(candidate.split())[:_MAX_CHARS]

    result = HypotheticalPassageResult(passage=passage, model=selected_model)
    _store(cache_key, result)
    return result


def _store(cache_key: str, result: HypotheticalPassageResult) -> None:
    with _hyde_cache_lock:
        _hyde_cache[cache_key] = result
        _hyde_cache.move_to_end(cache_key)
        while len(_hyde_cache) > _HYDE_CACHE_LIMIT:
            _hyde_cache.popitem(last=False)


def _clear_cache_for_tests() -> None:
    """Test-only hook so cached failures don't leak across tests."""
    with _hyde_cache_lock:
        _hyde_cache.clear()
